from __future__ import annotations

import os
from pathlib import Path


# Resolve project root relative to this file so paths stay stable from any cwd.
PROJECT_ROOT = Path(__file__).resolve().parents[2]
# Raw source currently used by pipeline.
DEFAULT_SOURCE_CSV = PROJECT_ROOT / "data" / "amazon.csv"
# Cleaned staging output generated by pipeline.
DEFAULT_STAGING_CSV = PROJECT_ROOT / "data" / "staging" / "amazon_clean.csv"


def load_dotenv_if_present(env_path: Path | None = None) -> None:
    """Load key=value pairs from .env into process env if missing."""
    # Use provided path if supplied, otherwise default to project .env.
    env_file = env_path or (PROJECT_ROOT / ".env")
    if not env_file.exists():
        return

    # Parse simple KEY=VALUE lines and ignore comments/blank lines.
    for line in env_file.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        # Do not overwrite variables that are already present in the shell.
        if key and key not in os.environ:
            os.environ[key] = value


def get_database_url() -> str:
    # Ensure environment variables are loaded before building the URL.
    load_dotenv_if_present()
    # Read Postgres settings with safe defaults for local Docker development.
    host = os.getenv("POSTGRES_HOST", "localhost")
    port = os.getenv("POSTGRES_PORT", "5432")
    db = os.getenv("POSTGRES_DB", "amazon_sales")
    user = os.getenv("POSTGRES_USER", "postgres")
    password = os.getenv("POSTGRES_PASSWORD", "amazon_pwd")
    # SQLAlchemy connection string format for psycopg2 driver.
    return f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{db}"
